// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230404101742_Seed-data")]
    partial class Seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Students", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("38b69e88-e7bf-4fec-b582-c9636fd66bc7"),
                            Name = "Student1",
                            Roll = "1001"
                        },
                        new
                        {
                            StudentId = new Guid("3c4c04e0-5f49-452a-9468-f4056578358b"),
                            Name = "Student2",
                            Roll = "1002"
                        },
                        new
                        {
                            StudentId = new Guid("fa8533a2-0897-4279-b0fa-46a4a3a54b74"),
                            Name = "Student3",
                            Roll = "1003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
